Use std::array instead of T[] to avoid clang-tidy warnings
chainerx/chainerx/build/googletest-src/googletest/include/gtest/gtest.h:1392:11: error: The left operand of == is a garbage value [clang-analyzer-core.UndefinedBinaryOperatorResult,-warnings-as-errors]
  if (lhs == rhs) {
          ^
chainerx/chainerx/chainerx/routines/creation_test.cc:352:5: note: Calling RunTestWithThreads
    testing::RunTestWithThreads([&shape, &dtype, &host_data, &strides, &offset, &device]() {