change links __init__.py to include the caffe
The links __init__.py file didn't include reference to the caffe module and thus importing such as `from chainer import links as L` then referencing objects in the caffe module as `L.caffe.CaffeFunction` threw an error.

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-2-cc0cfc514d8a> in <module>()
----> 1 L.caffe.CaffeFunction

AttributeError: 'module' object has no attribute 'caffe'
```

Changed the link __init__.py to include `from chainer.links import caffe`